#!/usr/bin/env python3

import re

re_course = r"(\w{2,4}) *(\d{3}\w*)"
prog_course = re.compile(re_course)
prog_course_and_title = re.compile(re_course + r"[ -:]+(.+)")

subjects = {
    'AAAS': 'Asian Asian Am Study',
    'ACCT': 'Accounting',
    'AFST': 'Africana Studies',
    'AMS': 'Ancient Mediterranean St',
    'ANTH': 'Anthropology',
    'ARAB': 'Arabic',
    'ARTH': 'Art History',
    'ARTS': 'Studio Art',
    'ASTR': 'Astronomy',
    'BCHM': 'Biochemistry',
    'BIOL': 'Biology',
    'BLS': 'Business Law and Society',
    'BME': 'Biomedical Engineering',
    'CCPA': 'Col Comm & Public Affairs',
    'CDCI': 'Career Dev Ctr Internship',
    'CHEM': 'Chemistry',
    'CHIN': 'Chinese',
    'CINE': 'Cinema',
    'COLI': 'Comparative Literatr',
    'CQS': 'Comp and Quant Skills',
    'CS': 'Computer Science',
    'CSC': 'Comm Schools Cert',
    'CW': 'Creative Writing',
    'DATA': 'Data Analytics',
    'ECON': 'Economics',
    'EDD': 'Engineering Design Div',
    'EDUC': 'Education',
    'EECE': 'Elec Eng Comput Eng',
    'EGYN': 'Egyptian',
    'ELED': 'Elementary Education',
    'ELI': 'English Language Inst',
    'ENG': 'English',
    'ENT': 'Entrepreneurship',
    'ENVI': 'Environmental Study',
    'ERED': 'Early Childhood Educ',
    'EVOS': 'Evolutionary Studies',
    'FIN': 'Finance',
    'FREN': 'French',
    'GEOG': 'Geography',
    'GEOL': 'Geology',
    'GERM': 'German',
    'GLST': 'Global Studies',
    'GMAP': 'Genocide&Mass Atr Prev',
    'GRD': 'Graduate',
    'GRK': 'Greek',
    'HARP': 'Harpur College Wide',
    'HDEV': 'Human Development',
    'HEBR': 'Hebrew',
    'HIST': 'History',
    'HMRT': 'Human Rights',
    'HSCI': 'Health Sciences',
    'HWS': 'Health and Wellness St',
    'IBUS': 'Internatnl Business',
    'INFO': 'Information Systm',
    'ISE': 'Industr and Systm Engr',
    'ISRL': 'Israel Studies',
    'ITAL': 'Italian',
    'JPN': 'Japanese',
    'JUST': 'Judaic Studies',
    'KOR': 'Korean',
    'LACS': 'Lat Amer and Carib Study',
    'LAT': 'Latin',
    'LEAD': 'Leadership',
    'LING': 'Linguistics',
    'LTRC': 'Literacy',
    'LXC': 'LXC',
    'MATH': 'Mathematics & Statistics',
    'MDVL': 'Medieval Studies',
    'ME': 'Mechanical Engineering',
    'MGMT': 'Management',
    'MIS': 'Mgmt Info Systems',
    'MKTG': 'Marketing',
    'MSE': 'Material Science Eng',
    'MSHR': 'MS Human Rights',
    'MUS': 'Music',
    'MUSP': 'Music Performance',
    'NURS': 'Nursing',
    'OCT': 'Occupational Therapy',
    'OPM': 'Mgmt Operations',
    'OUT': 'Outdoor Pursuits',
    'PAFF': 'Public Affairs',
    'PERS': 'Persian',
    'PH': 'Public Health',
    'PHIL': 'Philosophy',
    'PHRM': 'Pharmacy',
    'PHSC': 'Pharmaceutical Sciences',
    'PHYS': 'Physics',
    'PIC': 'Phil Interp Culture',
    'PLSC': 'Political Science',
    'PPL': 'Phil Politics and Law',
    'PSYC': 'Psychology',
    'RELG': 'Religious Studies',
    'RHET': 'Rhetoric',
    'RLIT': 'Romance Literature',
    'ROML': 'Romance Langs and Lit',
    'RPHL': 'Romance Philology',
    'RUSS': 'Russian',
    'SAA': 'Student Affairs Admin',
    'SCHL': 'BUniv Scholars Courses',
    'SCM': 'Supply Chain Management',
    'SEC': 'Secondary Education',
    'SLP': 'Speech & Lang Pathology',
    'SOC': 'Sociology',
    'SPAN': 'Spanish',
    'SPED': 'Special Education',
    'SSIE': 'SS and Industrial Engr',
    'SUST': 'Sustainable Communities',
    'SW': 'Social Work',
    'THEA': 'Theater',
    'THEP': 'Theater Performance',
    'Transfer': 'ENG',
    'TRIP': 'Translation Research',
    'TURK': 'Turkish',
    'UNIV': 'Univ Wide Courses',
    'WGSS': 'Women, Gender & Sexuality',
    'WRIT': 'Writing',
    'WTSN': 'Engineering Design',
    'YIDD': 'Yiddish'
}
